### ISSUE TITLE
Implement Lab "Data compression fundamentals: LZ77"

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [vicente-gonzalez-ruiz/teaching#6]
See https://github.com/manassra/LZ77-Compressor/blob/master/src/LZ77.py

Evaluate the code as in https://github.com/vicente-gonzalez-ruiz/teaching/blob/master/compression/00-text/01-gzip.ipynb

**Comment by sergiocaceres** [comment]
I will try it

**Comment by claudio382** [comment]
Trying to solve issue number 6.

**Comment by vicente-gonzalez-ruiz** [comment]
Forget the last comment. This issue is open because the current implementation does not fit the original version of the algorithm and because the file `input.txt` is missing.

**Comment by Luis8811** [comment]
Ill try to solve the issue.

**Comment by vicente-gonzalez-ruiz** [comment]
Moved to: https://github.com/Sistemas-Multimedia/slides
