### ISSUE TITLE
Implement Lab "Data compression fundamentals: LZ78"

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [vicente-gonzalez-ruiz/teaching#7]
See https://gist.github.com/mreid/7207103

Evaluate the code as in https://github.com/vicente-gonzalez-ruiz/teaching/blob/master/compression/00-text/01-gzip.ipynb

**Comment by claudio382** [comment]
Trying to solve it.

**Comment by claudio382** [comment]
Done.

**Comment by vicente-gonzalez-ruiz** [comment]
Thanks again, @claudio382
