### ISSUE TITLE
Implementing Lab "Data compression fundamentals: LZW"

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [vicente-gonzalez-ruiz/teaching#8]
See https://rosettacode.org/wiki/LZW_compression#Python

Evaluate the code as in https://github.com/vicente-gonzalez-ruiz/teaching/blob/master/compression/00-text/01-gzip.ipynb (we want to compare LZW with the rest of compression algorithms).

Don't forget to run `make` in the directory `teaching/compression/00-text/01-gzip` to get the images of the corpus.

**Comment by claudio382** [comment]
Trying to solve this issue.

**Comment by claudio382** [comment]
Done.

**Comment by vicente-gonzalez-ruiz** [comment]
Thank you, @claudio382 !
