### ISSUE TITLE
Implements a Lab similar to https://github.com/vicente-gonzalez-ruiz/teaching/blob/master/compression/00-text/01-gzip.ipynb but using bzip2

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [vicente-gonzalez-ruiz/teaching#9]

**Comment by sergiocaceres** [comment]
Where can I solve in the notes this issue? (Lab number[?])
Thanks!

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @sergiocaceres, do you mean in which file? In: https://github.com/vicente-gonzalez-ruiz/teaching/blob/master/compression/00-text/01-gzip.ipynb

**Comment by vicente-gonzalez-ruiz** [comment]
Moved to: https://github.com/Sistemas-Multimedia/slides
